In [2]:
from ehrpredict import EHRPredict
import pandas as pd

# for testing, it's probably going to be easier to just create an instance of your model class directly
# especially because we haven't figured out library version stuff and it will probably get mad at you when you try to import EHRPredict

# from models.chf.chfmodel import CHFModel
# model = CHFModel()
# result = model.run(data)    # <-- uses run from the parent class

In [3]:
EHRPredict.get_data_format('congestive heart failure')

{'icd_codes': ['date_icd', 'icd', 'bdsp_patient_id'],
 'medications': ['date_med_start', 'date_med_end', 'med', 'bdsp_patient_id'],
 'notes': ['date_note', 'note', 'bdsp_patient_id']}

In [4]:
data = {
    'icd_codes' : pd.read_csv('example_data/icd_codes.csv'),
    'medications' : pd.read_csv('example_data/medications.csv'),
    'notes' : pd.read_csv('example_data/notes.csv')
}

In [11]:
model = EHRPredict()
result = model.predict('congestive heart failure', data)
pd.concat(result, axis=1)

Ignoring unknown columns in icd_codes: Unnamed: 0, diagnosisnm, bdspencounterid, Unnamed: 0.1, ICDType, ICDdsc
Ignoring unknown columns in medications: Unnamed: 0, bdspencounterid, Unnamed: 0.1
Ignoring unknown columns in notes: Unnamed: 0, annot, hospital, group
2024-07-24 18:47:15,926	INFO worker.py:1740 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265

,bdsp_patient_id,date_note,note,icd+,med+,428,I50,Lisinopril,furosemide,bumetanide,...,Dyrenium,Adderall,Midrin,ipratropium,sertraline,valium,levoxyl,prob_chf_0,prob_chf_1,predict_class_chf
0,114734863.0,2022-11-12,********* clinic note */*/**** 11: 00...,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0.916835,0.083165,0

In [12]:
import logging
logging.basicConfig(level=logging.INFO) # use this to get a bit more info out


model = EHRPredict()
result = model.predict('congestive heart failure', icd_codes=data['icd_codes'], medications=data['medications'], notes=data['notes']) # this also works, the kwargs are pulled from your data format
pd.concat(result, axis=1)

INFO:models.chf.chfmodel:Initializing model
INFO:models.chf.chfmodel:Finished initializing model
INFO:models.chf.chfmodel:Preprocessing data
WARNING:models.chf.chfmodel:Ignoring unknown columns in icd_codes: Unnamed: 0, diagnosisnm, bdspencounterid, Unnamed: 0.1, ICDType, ICDdsc
WARNING:models.chf.chfmodel:Ignoring unknown columns in medications: Unnamed: 0, bdspencounterid, Unnamed: 0.1
WARNING:models.chf.chfmodel:Ignoring unknown columns in notes: Unnamed: 0, annot, hospital, group
INFO:models.chf.chfmodel:Generating features
2024-07-24 18:49:20,338	INFO worker.py:1740 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
INFO:models.chf.chfmodel:Getting model predictions

,bdsp_patient_id,date_note,note,icd+,med+,428,I50,Lisinopril,furosemide,bumetanide,...,Dyrenium,Adderall,Midrin,ipratropium,sertraline,valium,levoxyl,prob_chf_0,prob_chf_1,predict_class_chf
0,114734863.0,2022-11-12,********* clinic note */*/**** 11: 00...,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0.916835,0.083165,0